// Generated by CoffeeScript 1.3.3
(function() {

  this.Setup = require('./setup').Setup;

  this.Project = require('./project').Project;

  this.Downloader = require('./downloader').Downloader.Downloader;

}).call(this);
